Add prometheus gem and generate metrics endpoint
ministryofjustice/laa-court-data-ui pull request #307
Opened 2020-10-14 08:06 UTC by kmahern

#### What

#### Ticket

[board ticket description](link)

#### Why

#### How

--------

#### TODO (wip)

 - [ ] item 1
 - [X] item 2

2020-10-20 08:27 UTC, jsugarman commented on .k8s/dev/service.yaml
> +      name: metrics
This seems wrong and likely to break stuff. This is the app/web-app service. Should there not be a separate service for metrics?

2020-10-20 08:28 UTC, jsugarman commented on .k8s/production/service.yaml
> +      name: metrics
[ditto](https://github.com/ministryofjustice/laa-court-data-ui/pull/307/files#r508307575)

2020-10-20 08:28 UTC, jsugarman commented on .k8s/staging/service.yaml
> +      name: metrics
[ditto](https://github.com/ministryofjustice/laa-court-data-ui/pull/307/files#r508307575)

2020-10-20 08:29 UTC, jsugarman commented on .k8s/uat/service.yaml
> +      name: metrics
[ditto](https://github.com/ministryofjustice/laa-court-data-ui/pull/307/files#r508307575)

2020-10-20 08:35 UTC, jsugarman requested changes
Not sure this is correct. reusing the web app `service` for metrics seems odd and like it would break stuff. also can you add a fuller description to the PR of what this is doing

2020-10-22 12:47 UTC, kmahern commented
I have reverted the name change of port 80 in service.yaml from metrics to http.

2020-10-23 16:02 UTC, jsugarman approved these changes
👍  is this still available on `localhost:3000/metrics` endpoint

2020-10-26 07:21 UTC, merged